### OrthoTreesUppmax: Getting orthologs of the Podospora complex
# ===========================================================================
# Sandra Lorena Ament Velasquez
# 2023/08/09
# ++++++++++++++++++++++++++++++++++++++++++++++

# Excluding "PODAN" and "PODCO" which are included no matter what
SampleIDs: ["CBS112042p", "CBS237.71m", "CBS411.78m", "CBS415.72m", "PaTgp", "PaWa137m", "PaYp", "PcWa139m", "CBS124.78p", "PaWa100p", "PaWa21m", "PaWa28m", "PaWa46p", "PaWa53m", "PaWa58m", "PaWa63p", "PaWa87p", "CBS253.71p", "CBS333.63p", "CBS451.62p", "PcWa131m", "PcWa132p", "PcWa133m", "PaZp", "CBS433.50p", "CBS455.64m"]

# Repeat OrthoFinder with just one representative strain per species for root-inference
SpeciesTreeSamples: ["CBS112042p", "CBS237.71m", "CBS411.78m", "CBS415.72m", "CBS124.78p", "PODAN", "PODCO"]

assembliespath: "path/to/genomes"
annotationpath: "path/to/annotation"

# Data of P. anserina and P. comata reference genomes
PODAN: "../1_Annotation_v3/data/Podans_v2016/genomePodoMatPlus.fasta"
PODANgff: "../1_Annotation_v3/data/Podans_v2016/genome_annotation_PODANS_v2016.gff"
PODANgenes: "data/PODAN_genes.fas"
PODCO: "path/to/Podospora_comata/PODCO_genomic.fas"
PODCOgff: "path/to/Podospora_comata/PODCO_genomic.gff3"

